spring.application.name=locallens-backend

# H2 Database
spring.datasource.url=jdbc:h2:mem:locallensdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=shalu
spring.datasource.password=shalu

# JPA Settings
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Backend Port
server.port=8080

# React Frontend Access
spring.mvc.cors.allowed-origins=http://localhost:3000


